import { marked } from 'marked';
import hljs from 'highlight.js/lib/core';
import bash from 'highlight.js/lib/languages/bash';
import python from 'highlight.js/lib/languages/python';
import javascript from 'highlight.js/lib/languages/javascript';
import typescript from 'highlight.js/lib/languages/typescript';
import http from 'highlight.js/lib/languages/http';
import json from 'highlight.js/lib/languages/json';
import yaml from 'highlight.js/lib/languages/yaml';
import sql from 'highlight.js/lib/languages/sql';
import kotlin from 'highlight.js/lib/languages/kotlin';
import powershell from 'highlight.js/lib/languages/powershell';
import xml from 'highlight.js/lib/languages/xml';
import plaintext from 'highlight.js/lib/languages/plaintext';
import type { Lang } from '../i18n/l.ts';

hljs.registerLanguage('bash', bash);
hljs.registerLanguage('sh', bash);
hljs.registerLanguage('shell', bash);
hljs.registerLanguage('python', python);
hljs.registerLanguage('py', python);
hljs.registerLanguage('javascript', javascript);
hljs.registerLanguage('js', javascript);
hljs.registerLanguage('typescript', typescript);
hljs.registerLanguage('ts', typescript);
hljs.registerLanguage('http', http);
hljs.registerLanguage('json', json);
hljs.registerLanguage('yaml', yaml);
hljs.registerLanguage('yml', yaml);
hljs.registerLanguage('sql', sql);
hljs.registerLanguage('kotlin', kotlin);
hljs.registerLanguage('powershell', powershell);
hljs.registerLanguage('xml', xml);
hljs.registerLanguage('html', xml);
hljs.registerLanguage('plaintext', plaintext);
hljs.registerLanguage('text', plaintext);

export interface PostMeta {
  slug: string;
  title: string;
  date: string;          // YYYY-MM-DD
  summary: string;
  tags: string[];
  minutes?: number;
  sample?: boolean;
  draft?: boolean;
  /** Translated title/summary, generated by tools/blog-index.mjs from <slug>.<lang>.md files. */
  i18n?: Partial<Record<Exclude<Lang, 'en'>, { title: string; summary: string; minutes: number }>>;
}

export interface Post extends PostMeta {
  html: string;
  toc: { id: string; text: string; level: number }[];
  words: number;
  /** Language of the body that was actually loaded (falls back to English). */
  lang: Lang;
}

/** Title, summary and reading time for a list entry in the given language, falling back to English. */
export function pickMeta(p: PostMeta, lang: Lang) {
  const tr = lang === 'en' ? undefined : p.i18n?.[lang];
  return { title: tr?.title ?? p.title, summary: tr?.summary ?? p.summary, minutes: tr?.minutes ?? p.minutes, translated: lang === 'en' || !!tr };
}

const escapeHtml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

marked.use({
  gfm: true,
  breaks: false,
  renderer: {
    code(token: { text: string; lang?: string } | string, infostring?: string) {
      const text = typeof token === 'string' ? token : token.text;
      const raw = (typeof token === 'string' ? infostring : token.lang) || '';
      const lang = raw.split(/\s+/)[0].toLowerCase();
      const known = lang && hljs.getLanguage(lang);
      let body: string;
      try {
        body = known ? hljs.highlight(text, { language: lang }).value : escapeHtml(text);
      } catch {
        body = escapeHtml(text);
      }
      const label = lang ? `<span class="code-lang">${escapeHtml(lang)}</span>` : '';
      return `<div class="code-block">${label}<button class="code-copy" type="button" data-copy aria-label="Copy code">copy</button><pre><code class="hljs language-${escapeHtml(lang || 'text')}">${body}</code></pre></div>`;
    },
  },
});

/** Parses a leading YAML-ish front-matter block (simple key: value pairs, arrays as [a, b]). */
export function parseFrontMatter(src: string): { data: Record<string, unknown>; body: string } {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return { data: {}, body: src };
  const data: Record<string, unknown> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+)\s*:\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    let value: unknown = kv[2].trim();
    if (typeof value === 'string') {
      if (value.startsWith('[') && value.endsWith(']')) {
        value = value.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
      } else if (/^(true|false)$/i.test(value)) {
        value = value.toLowerCase() === 'true';
      } else {
        value = value.replace(/^["']|["']$/g, '');
      }
    }
    data[key] = value;
  }
  return { data, body: src.slice(m[0].length) };
}

function slugify(s: string) {
  return s.toLowerCase().replace(/<[^>]+>/g, '').replace(/[^a-z0-9\s-]/g, '').trim().replace(/\s+/g, '-').slice(0, 64);
}

export function renderPost(slug: string, src: string, lang: Lang = 'en'): Post {
  const { data, body } = parseFrontMatter(src);
  const words = body.split(/\s+/).filter(Boolean).length;
  const html = marked.parse(body, { async: false }) as string;
  // add ids to headings and build a table of contents
  const doc = new DOMParser().parseFromString(`<div id="w">${html}</div>`, 'text/html');
  const wrap = doc.getElementById('w')!;
  const toc: Post['toc'] = [];
  const seen = new Set<string>();
  wrap.querySelectorAll('h2, h3').forEach((h) => {
    let id = slugify(h.textContent || 'section') || 'section';
    let n = 1;
    while (seen.has(id)) id = `${id}-${++n}`;
    seen.add(id);
    h.id = id;
    const a = doc.createElement('a');
    a.href = `#${id}`;
    a.className = 'heading-anchor';
    a.setAttribute('aria-label', 'Link to this section');
    a.textContent = '#';
    h.appendChild(a);
    toc.push({ id, text: h.textContent?.replace(/#$/, '').trim() || id, level: h.tagName === 'H2' ? 2 : 3 });
  });
  wrap.querySelectorAll('a[href^="http"]').forEach((a) => { a.setAttribute('target', '_blank'); a.setAttribute('rel', 'noreferrer'); });
  wrap.querySelectorAll('img').forEach((img) => { img.setAttribute('loading', 'lazy'); });
  wrap.querySelectorAll('table').forEach((t) => { const d = doc.createElement('div'); d.className = 'table-wrap'; t.replaceWith(d); d.appendChild(t); });

  const tags = Array.isArray(data.tags) ? (data.tags as string[]) : [];
  return {
    slug,
    title: String(data.title ?? slug),
    date: String(data.date ?? ''),
    summary: String(data.summary ?? ''),
    tags,
    sample: data.sample === true,
    draft: data.draft === true,
    minutes: Math.max(1, Math.round(words / 220)),
    words,
    html: wrap.innerHTML,
    toc,
    lang,
  };
}

let indexCache: Promise<PostMeta[]> | null = null;
export function loadPostIndex(): Promise<PostMeta[]> {
  if (!indexCache) {
    indexCache = fetch('/blog/posts.json', { cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : []))
      .then((list: PostMeta[]) => list.filter((p) => !p.draft).sort((a, b) => (a.date < b.date ? 1 : -1)))
      .catch(() => []);
  }
  return indexCache;
}

/**
 * Fetches a markdown file, or null when it does not exist. The Accept header
 * and content-type check matter in dev: Vite answers unknown paths with
 * index.html (status 200) unless the request refuses HTML.
 */
const fetchMarkdown = (file: string): Promise<string | null> =>
  fetch(`/blog/posts/${file}`, { cache: 'no-cache', headers: { Accept: 'text/markdown, text/plain' } })
    .then((r) => (r.ok && !(r.headers.get('content-type') ?? '').includes('text/html') ? r.text() : null))
    .catch(() => null);

const postCache = new Map<string, Promise<Post | null>>();
/** Loads `<slug>.<lang>.md` when it exists, otherwise the English `<slug>.md`. */
export function loadPost(slug: string, lang: Lang = 'en'): Promise<Post | null> {
  if (!/^[a-z0-9-]+$/i.test(slug)) return Promise.resolve(null);
  const key = `${lang}:${slug}`;
  if (!postCache.has(key)) {
    const translated = lang === 'en' ? Promise.resolve<string | null>(null) : fetchMarkdown(`${slug}.${lang}.md`);
    postCache.set(key, translated
      .then((txt) => (txt ? { txt, lang } : fetchMarkdown(`${slug}.md`).then((en) => (en ? { txt: en, lang: 'en' as Lang } : null))))
      .then((r) => (r ? renderPost(slug, r.txt, r.lang) : null))
      .catch(() => null));
  }
  return postCache.get(key)!;
}

export function formatDate(iso: string, lang: Lang = 'en') {
  if (!iso) return '';
  const d = new Date(iso + 'T00:00:00');
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(lang === 'id' ? 'id-ID' : 'en-AU', { day: 'numeric', month: 'short', year: 'numeric' });
}
